= Общие сведения о модуле

Настоящий раздел документации описывает администрирование модуля _{am}_.

[#package]
== Состав установочного комплекта

. Пакет установки модуля: `{dv} ArchiveManagement server.msi`.

[#purpose]
== Назначение и функции модуля

Модуль _{am}_ является дополнительным модулем системы {dv}, который предназначен для организации упорядоченного архивного хранения электронных документов, ведения номенклатуры дел, распределения документов по разделам и делам номенклатур. Модуль работает со всеми БД, поддерживаемыми модулем _Платформа_, включая {pgsql}.

.Модуль предоставляет следующие возможности:
* Формирование структуры номенклатуры дел с помощью _Справочника номенклатуры дел_.
* Списание документов в дела.

****
Описание работы пользователя с функциями модуля _{am}_ приведено в пользовательской документации модуля. Работа с модулем в {wincl}е не поддерживается.
****

[#doc-structure]
== Как организована документация

.Документация модуля содержит следующие разделы:
. Общие сведения -- общая информация о модуле.
. xref:requirements.adoc[] -- требования к программному и аппаратному обеспечению компьютера, к системе {dv} для установки модуля.
. xref:module-structure.adoc[Структура модуля] -- перечислены компоненты, составляющие модуль.
. xref:admin:install.adoc[Установка] -- инструкция по установке, первоначальной настройке и удалению модуля.
. xref:admin:administration.adoc[Функции администратора] -- перечисление основных функций администратора модуля.
. Работа с функциями модуля _{am}_ со стороны пользователя приведена в пользовательской документации модуля.
