= Функции администратора

При установке модуля _{am}_ в систему {dv} будут загружены стандартные настройки (роли, состояния).

WARNING: Изменение стандартных настроек не допускается.

.Администратору системы разрешается:
* Настраивать дискреционные права доступа к узлам Справочника номенклатуры делfootnote:[Пользовательский интерфейс настройки дискреционных прав доступа реализован в _{wc}е_.].
* Создавать новые роли для работы с карточками _Архивное дело_, изменять и удалять созданные роли.

.Работа с функциями модуля осуществляется в {wc}е:
. При установке {wc}а должны быть установлены компоненты _{am}_. См. xref:webclient:admin:install-server.adoc#archive[документацию по администрированию модуля "{wc}"].
. В основное меню должна быть добавлена ссылка для открытия Справочника номенклатуры дел. В разметку карточек Документ должен быть добавлен элемент управления для списания в дело. См. пользовательскую документацию xref:webclient:user:docs-to-case.adoc[модуля "{wc}"].

[#view-docs]
== Просмотр документов, списанных в дело

Чтобы просматривать документы, списанные в дело, в карточке _Архивное дело_ должен находиться элемент управления `_Отображение документов_` (доступен только для карточки Архивное дело и только при установке модуля {am}).
ЭУ выводит все документы, добавленные в дело из первого найденного тома
данного дела. Том создаётся автоматически при добавлении в дело первого
документа. Подробнее элемент управления описан в документации модуля {wc}, см. подробнее раздел "xref:webclient:layouts:ctrl/nomenclatureOfCases/documentView.adoc[Отображение документов]".

[#view-cases]
== Просмотр дел, в которые списан документ

Чтобы видеть, в какие дела списан текущий документ, в карточки вида _Документ УД_ необходимо добавить элемент управления `_Дело_`. Элемент управления позволяет списывать текущий документ в выбранное дело Справочника номенклатуры дел, а также отображает дела, в которые списан документ. Подробнее элемент управления описан в документации модуля {wc}, см. раздел "xref:webclient:layouts:ctrl/nomenclatureOfCases/archiveCase.adoc[Дело]".
