= Настройка роли "Ответственного за дело"

Чтобы сотрудники имели возможность просматривать документы, списанные в дело, в справочнике "Конструктор ролей" администратор должен будет настроить карточки, которые планируется списывать в дело. Для карточки необходимо задать настройку для хранимой процедуры `dvam_Operand_IsResponsibleCaseDocument`.

Хранимая процедура `dvam_Operand_IsResponsibleCaseDocument` поставляется вместе с модулем. Процедура находит карточку дела, в которой есть ссылка на текущую карточку и определяет есть ли пользователь в списке ответственных за дело. +
Таким образом появляется возможность предоставить ответственным за дело сотрудникам права на чтение списанных в дело карточек.

.Чтобы настроить роль ответственного за дело:
. Откройте справочник _Конструктор ролей_.
. Выберите карточки, для которых должна быть доступна возможность списания в дело.
. Для выбранных карточек выполните настройку роли: `Я равно dvam_Operand_IsResponsibleCaseDocument`.

****
Подробнее о настройке ролей в документации _Описание конструкторов и справочников_ модуля _{bo}_, см. раздел xref:dev@desdirs:roles:role-model.adoc[].
****