= Обновление модуля

include:webclient:ROOT:partial$excerpts.adoc[tags=what-changed]

[#conditions]
== Условия обновления

* Установка новой версии должна выполняться в нерабочее время.
* Создайте резервную копию БД {dv}.
* База данных {dv} должна быть переведена на работу с расширенными метаданными.
* При обновлении версия клиентского дистрибутива должна быть равной версии серверного дистрибутива.
* Если к новой версии модуля приложена инструкция по обновлению, следуйте ей.
* *Если комплект обновления включает обновление для модуля "{pl}"*, перейдите к инструкции, приведенной xref:5.5.5@platform:admin:update-module.adoc[в документации] модуля {pl}.

[#update]
== Порядок обновления

.Чтобы установить новую версию модуля:
. Создайте резервную копию БД.
include::system::partial$stop.adoc[]
. Перед продолжением установите новые версии других модулей {dv}, если таковые включены в комплект обновления.
. Установите серверную часть модуля.
. На последнем шаге выберите базы данных, в которых будут обновлены библиотеки карточек модуля, и нажмите *ОК*, чтобы запустить процесс обновления БД.
+
.По завершении обновления:
* Будет показано окно с результатом обновления.
* Сервисы {dv} будут перезапущены.
+
. Установите новую версию модуля БЕЗ обновления БД (со снятым флагом `*Обновить базу данных*`):
+
* На оставшихся узлах кластера {dv}.
* На сервере СУБП, {wc}а и других модулей, использующих компоненты модуля _{am}_.
